#!/usr/bin/env zsh
# Sourced from ~/.zshrc to load this dotfile repo's zsh configuration

source "$(dirname "${(%):-%N}")/../inc/base.sh"
source "$DOTFILE_ROOT/inc/settings.sh"
source "$DOTFILE_ROOT/inc/zsh/statusbar.zsh"
source "$DOTFILE_ROOT/inc/zsh/completion.zsh"

[ -f "$DOTFILE_ROOT/inc/local.sh" ] && source "$DOTFILE_ROOT/inc/local.sh"
